let suggestions = [
    "Hikari Sushi",
    "McDonalds",
    "Jack in the Box",
    "Chilis",
    "Dunkin Donuts",
    "Rincome Restaurants",
    "Boba Snow House",
    "Rococo Ramen",
    "Outback Steakhouse",
    "Presidente Restaurant",
    "Good Pho You",
    "Maru Ramen",
    "Truman House Tavern",
    "Gen Korean BBQ House",
    "Applebee's Grill + Bar",
    "Buffalo Wild Wings",
    "TGI Fridays",
    "Finney's Crafthouse-Porter Ranch",
    "Gus's BBQ",
    "Domino's Pizza",
    "Chipotle Mexican Grill",
    "PokiMX (San Fernando)",
    "Bar Louie-Northridge Fashion Center",
    "Porto's Bakery and Cafe",
    "Yard House",
    "Wood Ranch",
    "Los Tres Hermanos Bar & Grill",
    "El Torito",
    "Fishbowl Poke Co.",
    "California Pizza Kitchen at Northridge",
    "Ceviches mariscos estilo Nayarit",
    "SUSHIRAW",
    "Asahi Sushi",
    "Blue Palms Brewhouse",
    "San Fernando Brewing Company",
    "Lucille's Smokehouse Bar-B-Que",
    "Lazy Dog Restaurant & Bar",
    "Marci's Sports Bar & Grill",
    "BJ's Restaurant & Brewhouse",
    "Red Robin Gourmet Burgers and Brews",
    "Dave & Buster's",
    "Wing Stop"
];