let suggestions = [
    "Hikari Sushi",
    "McDonalds",
    "Jack in the Box",
    "Chilis",
    "Dunkin Donuts",
    "Rincome Restaurants",
    "Boba Snow House",
    "Rococo Ramen",
    "Outback Steakhouse",
    "Presidente Restaurant",
    "Good Pho You",
    "Maru Ramen",
    "Truman House Tavern",
    "Gen Korean BBQ House",
    "Applebee's Grill + Bar",
    "Buffalo Wild Wings",
    "TGI Fridays",

];